### ISSUE TITLE
Add duty to assignment

### ISSUE THREAD

**Issue by Kasimir123** [namanshrimali/expertiza#3]
If an assignment is marked as a duty-based assignment during creation in the review strategy tab (most likely through the use of the checkbox from [issue 2]) then a button or link will appear with the text "add duty".

If the button or link is clicked a text field opens up into which a role name can be typed and another button is created captioned "Add role (duty)". 

When the text field is filled out and the button is pressed the role gets added to the list of roles that appears on the review strategy tab.

**Comment by kanchan110295** [comment]
The above issue is updated and can be found in 'Duty Creation Page'
